name: cicd

on:
  push:
    branches: [master]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Docker image Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE_NAME}}:latest
          push-args: --disable-content-trust
            
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:      
      - name: remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{secrets.EC2_IP}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          port: ${{secrets.EC2_SSH_PORT}}
          script: |
            cd v8c
            docker-compose pull -q
            docker-compose up --force-recreate --build -d --quiet-pull
        
